[package]
name = "convert-content-farm-list"
version = "0.2.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
indoc = "1.0.9"
tap = "1.0.1"
time = {version = "0.3.26", features = ["formatting", "macros"]}
ureq = "2.7.1"
