[package]
name = "convert-content-farm-list"
version = "0.1.1"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.58"
indoc = "1.0.6"
tap = "1.0.1"
time = {version = "0.3.11", features = ["formatting", "macros"]}
ureq = "2.4.0"
