name: Update List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    name: Update List
    steps:
      - uses: robinraju/release-downloader@v1.8
        with: 
          repository: "DanSnow/convert-content-farm-list"
          latest: true
          fileName: convert-content-farm-list
          tarBall: false
          zipBall: false

      - name: Generate List
        env:
          UPDATE_URL: "https://raw.githubusercontent.com/DanSnow/convert-content-farm-list/gh-pages/content-farm-list.txt"
        run: |
          mkdir -p ./public
          chmod +x ./convert-content-farm-list
          ./convert-content-farm-list > ./public/content-farm-list.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
